2025-05-17 19:45:12 UTC
Windows-10-10.0.26100
Ren'Py 8.3.7.25031702

Early init took 0.05s
Loading error handling took 0.03s
Loading script took 0.14s
Loading save slot metadata took 0.03s
Loading persistent took 0.00s
Running init code took 0.03s
Loading analysis data took 0.01s
Analyze and compile ATL took 0.00s
Reloading save slot metadata took 0.02s
Index archives took 0.00s
Backing up script files to 'C:\\Users\\thoma\\AppData\\Roaming/RenPy/backups\\Bird that Flies High':
Dump and make backups took 0.03s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc took 0.04s
DPI scale factor: 1.250000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.29s
Cleaning stores took 0.00s
Init translation took 0.00s
Build styles took 0.00s
Load screen analysis took 0.00s
Analyze screens took 0.01s
Save screen analysis took 0.01s
Prepare screens took 0.04s
Save pyanalysis. took 0.00s
Save bytecode. took 0.02s
Running _start took 0.00s
Interface start took 0.59s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'NVIDIA GeForce RTX 2050/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 546.18'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1858, 1045) drawable=(1858, 1045)
Maximum texture size: 4096x4096
Screen sizes: virtual=(1920, 1080) physical=(1920, 1051) drawable=(1920, 1051)
Maximum texture size: 4096x4096
Screen sizes: virtual=(1920, 1080) physical=(1920, 1080) drawable=(1920, 1080)
Maximum texture size: 4096x4096

Full traceback:
  File "game/nerkk_cap4.rpy", line 180, in script
    jump bad_ending
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 1712, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'bad_ending'.

While running game code:
  File "game/nerkk_cap4.rpy", line 180, in script
    jump bad_ending
ScriptError: could not find label 'bad_ending'.

Full traceback:
  File "game/nerkk_cap4.rpy", line 183, in script
    jump bad_ending
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 1712, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'bad_ending'.

While running game code:
  File "game/nerkk_cap4.rpy", line 183, in script
    jump bad_ending
ScriptError: could not find label 'bad_ending'.

Full traceback:
  File "game/nerkk_cap4.rpy", line 266, in script
    nerkk "Temos que voltar logo para deter [pronome] [causa]"
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\character.py", line 1456, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\character.py", line 1369, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\character.py", line 1349, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'causa' is not defined

While running game code:
  File "game/nerkk_cap4.rpy", line 266, in script
    nerkk "Temos que voltar logo para deter [pronome] [causa]"
NameError: name 'causa' is not defined

Full traceback:
  File "game/nerkk_cap4.rpy", line 266, in script
    nerkk "Temos que voltar logo para deter [pronome] [causa]"
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\character.py", line 1456, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\character.py", line 1369, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\character.py", line 1349, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'causa' is not defined

While running game code:
  File "game/nerkk_cap4.rpy", line 266, in script
    nerkk "Temos que voltar logo para deter [pronome] [causa]"
NameError: name 'causa' is not defined

Full traceback:
  File "game/nerkk_cap4.rpy", line 292, in script
    jump bad_ending2
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 1712, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'bad_ending2'.

While running game code:
  File "game/nerkk_cap4.rpy", line 292, in script
    jump bad_ending2
ScriptError: could not find label 'bad_ending2'.

Full traceback:
  File "game/nerkk_cap4.rpy", line 298, in script
    jump bad_ending2
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\ast.py", line 1712, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\thoma\Downloads\renpy-8.3.6-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'bad_ending2'.

While running game code:
  File "game/nerkk_cap4.rpy", line 298, in script
    jump bad_ending2
ScriptError: could not find label 'bad_ending2'.
Cleaning stores took 0.00s
Init translation took 0.00s
Build styles took 0.00s
Load screen analysis took 0.03s
Analyze screens took 0.00s
Prepare screens took 0.00s
Running _start took 0.00s
Screen sizes: virtual=(1920, 1080) physical=(1920, 1051) drawable=(1920, 1051)
Maximum texture size: 4096x4096
Screen sizes: virtual=(1920, 1080) physical=(1920, 1080) drawable=(1920, 1080)
Maximum texture size: 4096x4096
